" configure indentation
filetype indent on
set tabstop=4
set shiftwidth=4
set softtabstop=4
set expandtab
set smartindent
set autoindent

" config nerdcommenter
let g:NERDSpaceDelims = 1

" add line numbers
set relativenumber number

" enable syntax highlighting
filetype plugin on

" keep buffer open and disable backups
set hidden
set nobackup
set nowritebackup

" enable mouse
set mouse=a

" configure autocompletion
set completeopt=menuone,noinsert

" setup themeing
colorscheme gruvbox
set laststatus=1
set showtabline=2
set nohlsearch
set scrolloff=8
set signcolumn=yes

" allow cursor to wrap
set whichwrap+=<,>,h,l,[,] 
