order = ["audio", "backlight", "battery", "time"]
separator = "  |  "

[audio]
mute = "ﱝ"
template = "{ICO} {VOL}%"
icons = ["奄", "奔", "墳"]

[backlight]
template = "{ICO}  {BL}%"
icons = ["", "", ""]

[battery]
charging = ""
discharging = ""
no_battery = ""
icons = ["", "", "", "", "", "", "", "", "", "", ""]

[time]
format = "%m/%d/%y %a %H:%M"

